### ISSUE TITLE
the GADRewardBasedVideoAd should update to 7.7.0

### ISSUE THREAD

**Issue by badboy-tian** [robovm/robovm-robopods#128]
current ios admob sdk version is 7.5.0

**Comment by nnkdev** [comment]
Hi tianqiujie,
Can you share the source code "init/load reward video ads" and "show reward video ads"?
Thanks and good day for you !

**Comment by badboy-tian** [comment]
@hoangtunho2611 this project has being abandoned. you can use this project: https://github.com/MobiDevelop/robovm-robopods

**Comment by hoangtunho2611** [comment]
@tianqiujie 
Yes, I'm using it. I used banners and interstitial ads. But I did not find anything with Reward Video. Can you guide me a little?
