### ISSUE TITLE
How do I use these bindings?

### ISSUE THREAD

**Issue by wsrdzg** [robovm/robovm-robopods#13]
It would be great if there was a small description how to integrate these bindings in a existing project.
A way to download this bindings as jar would also be great. Like here (https://github.com/BlueRiverInteractive/robovm-ios-bindings)

**Comment by mkarpoff** [comment]
if you go to the bottom of the voting page (http://robovm.com/robopods-voting-result-and-preview/) they explain how to setup and use the bindings. That being said it would be nice to have documentation for that.

**Comment by wsrdzg** [comment]
Ok, thanks. But I think it would be good to include or link the instructions to this GitHub project so other people can find it faster.

**Comment by BlueRiverInteractive** [comment]
You can find the robopods as jars here: https://oss.sonatype.org/content/repositories/snapshots/org/robovm/

There will be a small description on the readme of this repository soon. Also a more extensive entry will be added to the robodocs: docs.robovm.com

**Comment by BlueRiverInteractive** [comment]
Short description + usage has been added to the readme of this repository. A more comprehensive documentation page will be added to the docs in the future.

**Comment by voidstarfire** [comment]
Still lacking documentation and support for things the bindings included (like full screen advertising..)
