### ISSUE TITLE
Facebook SDK: FBSDKShareDialog not compiles.

### ISSUE THREAD

**Issue by ASMCOM** [robovm/robovm-robopods#14]
Error message:

    Receiver of non static @Bridge method org.robovm.pods.facebook.share.FBSDKShareDialogMode: java.lang.String toString() must either be a Struct or a NativeObject

Code:

    FBSDKShareLinkContent content = new FBSDKShareLinkContent();
    content.setContentURL(new NSURL("https://developers.facebook.com"));
    
    FBSDKShareDialog dialog = new FBSDKShareDialog();
    dialog.setFromViewController(rootViewController);
    dialog.setShareContent(content);
    dialog.setMode(FBSDKShareDialogMode.ShareSheet);
    dialog.setDelegate(new FBSDKSharingDelegate() {
    			
    	@Override
    	public void didFail(FBSDKSharing sharer, NSError error) {				
    	}
    			
    	@Override
    	public void didComplete(FBSDKSharing sharer, NSDictionary<?, ?> results) {				
    	}
    			
    	@Override
    	public void didCancel(FBSDKSharing sharer) {				
    	}
    });
    dialog.show();

**Comment by BlueRiverInteractive** [comment]
This should be fixed now.

**Comment by ASMCOM** [comment]
I'm still getting the same error

**Comment by ASMCOM** [comment]
@BlueRiverInteractive 
I'm still getting the same error

**Comment by BlueRiverInteractive** [comment]
Hi I think the new snapshot will be ready tomorrow. You can see here when the snapshots have been updated: https://oss.sonatype.org/content/repositories/snapshots/org/robovm/

**Comment by ASMCOM** [comment]
Thanks @BlueRiverInteractive

**Comment by badlogic** [comment]
I'll trigger a build, should be ready in 10 mins. Note that you'll need to
clear your Gradle cache for it to pull in the latest nightlies.

**Comment by ASMCOM** [comment]
Great! Thank you!

**Comment by ASMCOM** [comment]
@badlogic was it supposed to be working by now ?

**Comment by ASMCOM** [comment]
@badlogic  was it supposed to be working by now ? I'm still seeing the old bindings in my project...

**Comment by badlogic** [comment]
Terribly sorry, clicked the wrong button. Should be available in 5 mins
from SonaType!

**Comment by ASMCOM** [comment]
Great! I see the update now. Thanks!
