### ISSUE TITLE
Readme: List or explain how to know artifact name

### ISSUE THREAD

**Issue by rotter** [robovm/robovm-robopods#18]
Hello.

On the Readme you give an example for facebook (compile "org.robovm:robopods-facebook-ios:1.0.0-SNAPSHOT"), but nowhere I could find the artifact names for the other Robopods, or even for the facebook (if it wasnt written on the readme itself).

Please elaborate on the Readme on how to know the names of the artifacts, or list them all there.

Thanks

**Comment by BlueRiverInteractive** [comment]
Thanks for creating an issue. Creating a list with artifact names of all robopods is already on my todo, I am just waiting with that until the bindings are polished enough to be out of beta and ready for use.

In the meantime you can just open up the pom.xml of a robopod and get the artifactId there. They are very similarly named, like org.robovm:robopods-chartboost-ios:1.0.0-SNAPSHOT, org.robovm:robopods-google-analytics-ios:1.0.0-SNAPSHOT, etc.
