### ISSUE TITLE
Facebook ShareDialog Delegate

### ISSUE THREAD

**Issue by Yayo-Arellano** [robovm/robovm-robopods#21]
In this fragment of code when i try to share in facebook if the sharing is succesful the method didComplete is called, but if i cancel the ShareDialog the method didComplete is also called. The method didCancel is never called.
```java
FBSDKShareLinkContent link = new FBSDKShareLinkContent();
        link.setContentURL(new NSURL("https://itunes.apple.com/us/app/pony-racing/id776425427?ls=1&mt=8"));
        FBSDKShareDialog dialog = new FBSDKShareDialog();
        dialog.setShareContent(link);
        dialog.setDelegate(new FBSDKSharingDelegateAdapter() {
            @Override
            public void didComplete(FBSDKSharing sharer, NSDictionary<?, ?> results) {
               Gdx.app.log("FACEBOOK", "DID COMPLETE");
            }

            @Override
            public void didCancel(FBSDKSharing sharer) {
                Gdx.app.log("FACEBOOK", "DID CANCEL");
            }
        });
        dialog.show();
```

**Comment by BlueRiverInteractive** [comment]
It seems you will only get notified for didCancel, if the Facebook user is signed in: https://developers.facebook.com/docs/reference/ios/current/protocol/FBSDKSharingDelegate/

In particular
> The delegate is notified with the results of the sharer as long as the application has permissions to receive the information. For example, _**if the person is not signed into**_ the containing app, the sharer may _**not be able to distinguish between completion of a share and cancellation**_.

**Comment by Yayo-Arellano** [comment]
Thank you i did not read the documents before, i will see what can i do about this.

**Comment by BlueRiverInteractive** [comment]
I'll close this then as it's clearly not an issue with RoboVM, rather a "feature" of the Facebook SDK.
