### ISSUE TITLE
Readme versions automatically update with next release

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm-robopods#23]
We should have some script that updates the version in all readmes

**Comment by ntherning** [comment]
Add to the release jenkins job.

**Comment by BlueRiverInteractive** [comment]
The new README will explain how to set global version variables for the robopods. There will only be 2 versions in the main README that we need to update, all other READMEs will refer to the variables (`$robopodsVersion` or `${robopods.version}`).
 We can update those two versions in the main README by hand.
