### ISSUE TITLE
Failed to resolve: org.robovm:robopods-google-mobile-ads-ios:1.5.0-SNAPSHOT

### ISSUE THREAD

**Issue by molp** [robovm/robovm-robopods#24]
Hi,

I am trying to incorporate the mobile ads robopod, but it fails with the error message

    Error:Failed to resolve: org.robovm:robopods-google-mobile-ads-ios:1.5.0-SNAPSHOT

I am including the robopod via

    compile "org.robovm:robopods-google-mobile-ads-ios:1.5.0-SNAPSHOT"

Probably I am missing something obvious, maybe you can point it out for me?

**Comment by badlogic** [comment]
There are no 1.5.0-SNAPSHOT builds. Please use 1.5.0 release builds.

**Comment by BlueRiverInteractive** [comment]
For google-mobile-ads you can use 1.5.1-SNAPSHOT. There was a typo in the README which should be fixed now.
