### ISSUE TITLE
admob baner freeze and crash app

### ISSUE THREAD

**Issue by zielok** [robovm/robovm-robopods#30]
libGDX 1.6.4, roboVM 1.5.0, admob-1.5.1-SNAPSHOT

I try add robopods admob baner to my app. App after 20-30 seconds (I dont make anything in my app) - freezing for one second and then the application crashed. When I Use Admob1.0.0 binding for libgdx - my game works correctly.  
Changes in my code is:
- rename "import" admob,
- change create GADRequest

**Comment by keskin** [comment]
same problem here
it crashes randomly. could be related type of ads(text, image, video etc.)?
any luck with workaround?

**Comment by BlueRiverInteractive** [comment]
Could you please retry with the latest version? There have been some changes that may fixed the issue.

**Comment by zielok** [comment]
Now works correctly. I don't observe any crash.

**Comment by BlueRiverInteractive** [comment]
Glad it works now!
