### ISSUE TITLE
Failed to build libgdx games with facebook robopods

### ISSUE THREAD

**Issue by esqi** [robovm/robovm-robopods#31]
When trying to build libgdx ios application using gradle createIPA failed with this exception:
```Unresolved type variable T in parameter 1 of @Block method <org.robovm.pods.bolts.BFTask: org.robovm.pods.bolts.BFTask $m$continueWithBlock$(org.robovm.pods.bolts.BFTask,org.robovm.objc.Selector,org.robovm.objc.block.Block1)>```

I've included
```compile "org.robovm:robopods-facebook-ios:1.5.0"```
in my ```build.gradle```

**Comment by esqi** [comment]
solved by adding
```compile "org.robovm:robopods-bolts-ios:1.5.0"```
in ```build.gradle```

**Comment by badlogic** [comment]
@blueriverinteractive doesn't the facebook pod have a dependency on the
bold pod? If not, we should make it so :)
