### ISSUE TITLE
Facebook Invite -> @NotImplemented("appInviteDialog:didCompleteWithResults:")

### ISSUE THREAD

**Issue by tajny** [robovm/robovm-robopods#34]

**Comment by BlueRiverInteractive** [comment]
Could you please provide more details about the issue you have?

**Comment by tajny** [comment]
Sorry :) 

There seems to be two problems with invites ,

First try ( using FBSDKAppInviteDialogDelegateAdapter ) : 
```
FBSDKAppInviteDialog inviteDialog = new FBSDKAppInviteDialog();
		FBSDKAppInviteContent content = new FBSDKAppInviteContent();
		content.setAppLinkURL(new NSURL(appLinkURL));// = [NSURL URLWithString:@"https://www.mydomain.com/myapplink"];
//		content.setAppInvitePreviewImageURL(v); //optional
		if (inviteDialog.canShow()){
			FBSDKAppInviteDialogDelegateAdapter delegateAdapter = new FBSDKAppInviteDialogDelegateAdapter();
			FBSDKAppInviteDialog.show(content,delegateAdapter);
		}
```
result: native app launches, i can send invite, but app crashes trying to fire callback method 

```
2015-08-19 08:44:27.113 IOSLauncher[1281:294402] -[j_org_robovm_pods_facebook_share_FBSDKAppInviteDialogDelegateAdapter appInviteDialog:didCompleteWithResults:]: unrecognized selector sent to instance 0x1468b160
2015-08-19 08:44:27.116 IOSLauncher[1281:294402] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[j_org_robovm_pods_facebook_share_FBSDKAppInviteDialogDelegateAdapter appInviteDialog:didCompleteWithResults:]: unrecognized selector sent to instance 0x1468b160'
*** First throw call stack:
(0x241df49f 0x319f6c8b 0x241e48b9 0x241e27d7 0x24114058 0xdbab91 0xdbaa79 0xdba8d7 0xd7632d 0x24197c61 0x240f36d5 0x24e25129 0x277195f1 0x27909009 0x27900d7d 0x2a92a0d1 0x241a5d7d 0x241a5041 0x241a3b7b 0x240f13c1 0x240f11d3 0x2b4a90a9 0x276ff7b1 0xbc2de1 0xbc2443 0xbc1b3f 0x6138fb 0xd55e47 0xd4e95b 0xd5040f 0xd50465 0xd4a78b 0xd440d5 0x41a6d4)
libc++abi.dylib: terminating with uncaught exception of type NSException
AppLauncher failed with an exception:
java.lang.RuntimeException: The app crashed: Terminated due to signal 6. Check the device logs in Xcode (Window->Devices) for more info.
	at org.robovm.libimobiledevice.util.AppLauncher.pipeStdOut(AppLauncher.java:829)
	at org.robovm.libimobiledevice.util.AppLauncher.launchInternal(AppLauncher.java:734)
	at org.robovm.libimobiledevice.util.AppLauncher.launch(AppLauncher.java:1052)
	at org.robovm.compiler.target.ios.AppLauncherProcess$1.run(AppLauncherProcess.java:67)
```

Second try ( not using FBSDKAppInviteDialogDelegateAdapter , but pure interface - FBSDKAppInviteDialogDelegate) : 

```
FBSDKAppInviteDialogDelegate del = new FBSDKAppInviteDialogDelegate() {
			
			@Override
			@Method(selector = "appInviteDialog:didFailWithError:")
			void didFail(FBSDKAppInviteDialog appInviteDialog, NSError error) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			@Method(selector = "appInviteDialog:didCompleteWithResults:")
			public void didComplete(FBSDKAppInviteDialog appInviteDialog,
					NSDictionary<?, ?> results) {
				// TODO Auto-generated method stub
				
			}
		};
```

first problem here is missing 'public' on didFail when eclipse autocompletes interface, but when running this : 

```
FBSDKAppInviteDialog inviteDialog = new FBSDKAppInviteDialog();
		FBSDKAppInviteContent content = new FBSDKAppInviteContent();
		content.setAppLinkURL(new NSURL(appLinkURL));// = [NSURL URLWithString:@"https://www.mydomain.com/myapplink"];
//		content.setAppInvitePreviewImageURL(v); //optional
		if (inviteDialog.canShow()){
			
			FBSDKAppInviteDialogDelegate delegate = new FBSDKAppInviteDialogDelegate() {
				
				@Override
				@Method(selector = "appInviteDialog:didFailWithError:")
				public void didFail(FBSDKAppInviteDialog appInviteDialog, NSError error) {
					
				}
				
				@Override
				@Method(selector = "appInviteDialog:didCompleteWithResults:")
				public void didComplete(FBSDKAppInviteDialog appInviteDialog,
						NSDictionary<?, ?> results) {
					
				}
			};
			
			
			FBSDKAppInviteDialog.show(content,delegate);
		}
```

result: native invite window doesnt show, and exception is thrown : 

```
java.lang.ClassCastException: resolvers.IOSAdapterFacebook$2 cannot be cast to org.robovm.objc.ObjCObject
	at org.robovm.objc.ObjCObject$Marshaler.protocolToNative(ObjCObject.java:375)
	at org.robovm.pods.facebook.share.FBSDKAppInviteDialog.$m$showWithContent$delegate$(Native Method)
	at org.robovm.pods.facebook.share.FBSDKAppInviteDialog.show(FBSDKAppInviteDialog.java)
```

**Comment by WillCalderwood** [comment]
I'm assuming an issue with `FBSDKGameRequestDialog` is likely related to this? Callbacks are never fired using `FBSDKGameRequestDialogDelegateAdapter`, and I get the same `ClassCastException` using `FBSDKGameRequestDialogDelegate`. The code below never fires callbacks. @BlueRiverInteractive  If you'd like me to create a separate issue then please say so.

            FBSDKGameRequestDialog.show(content, new FBSDKGameRequestDialogDelegateAdapter() {
                @Override
                public void didComplete(FBSDKGameRequestDialog gameRequestDialog, NSDictionary<?, ?> results) {
                    Gdx.app.log(TAG, "GameRequestDialog onSuccess");
                }

                @Override
                public void didFail(FBSDKGameRequestDialog gameRequestDialog, NSError error) {
                    Gdx.app.log(TAG, "GameRequestDialog onError");
                }

                @Override
                public void didCancel(FBSDKGameRequestDialog gameRequestDialog) {
                    Gdx.app.log(TAG, "GameRequestDialog onCancel");
                }
            });

**Comment by BlueRiverInteractive** [comment]
Yes, I just checked it. The show methods need to keep a strong reference to the delegate otherwise they get GCed. Currently they don't do it, so you won't get callbacks or just some.
I will fix this. In the meantime, you can create a new instance of FBSDKGameRequestDialog / FBSDKAppInviteDialog and use setDelegate to make the callbacks work.

**Comment by tajny** [comment]
Yes, that way it works :) Remember that your class must extend NSObject , if not you will face a classcastexception

**Comment by WillCalderwood** [comment]
@BlueRiverInteractive Is this likely to be an issue in numerous places in the bindings? I'm getting lots of intermittent crashes, some appear to be related to Facebook and some to AdMob. I'm going through removing all anonymous type callbacks and holding references to them just in case. I think the number of crashes is reducing, but it's hard to say with intermittent problems.
