### ISSUE TITLE
Issue building with the latest RoboVM + Admob

### ISSUE THREAD

**Issue by WillCalderwood** [robovm/robovm-robopods#35]
I'm possibly doing something stupid here, but I can't see what. I've just migrated to the latest RoboVM, which was fine. I then removed my old admob bindings and switched to the RoboPods integration. After doing that I started getting the following build error running `launchIOSDevice`

    Element 'unhideSymbols' does not have a match in class org.robovm.compiler.config.Config at line 25

I assume it's got something to do with this file which references unhideSymbols at line 25
https://github.com/robovm/robovm-robopods/blob/master/google-mobile-ads/ios/src/main/robopods/META-INF/robovm/ios/robovm.xml

I can't work out what I can do to fix this, as it appears to be a conflict between the AdMob RoboPod config and what RoboVM is expecting.

That said, no one else appears to be having this issue, so if I'm being stupid then please tell me so and let me know how I can be less stupid. :-)

**Comment by tajny** [comment]
Have you changed gradle robovm plugin version too ? I had the same problem before

**Comment by WillCalderwood** [comment]
Perfect, thanks for that. :+1:
