### ISSUE TITLE
Facebook Open Graph Share not working

### ISSUE THREAD

**Issue by WillCalderwood** [robovm/robovm-robopods#37]
Porting the example from [here](https://developers.facebook.com/docs/sharing/opengraph/ios) for a basic share gives me this code:

    private void doSimpleShare(){
        FBSDKShareOpenGraphObject object = new FBSDKShareOpenGraphObject();
        object.putString("og:type", "books.book");
        object.putString("og:title", "A Game of Thrones");
        object.putString("og:description", "In the frozen wastes to the north of Winterfell, sinister and supernatural forces are mustering.");
        object.putString("books:isbn", "0-553-57340-3");

        FBSDKShareOpenGraphAction action = new FBSDKShareOpenGraphAction();
        action.setActionType("books.reads");
        action.putObject("books.book", object);

        FBSDKShareOpenGraphContent content = new FBSDKShareOpenGraphContent();
        content.setPreviewPropertyName("books.book");
        content.setAction(action);

        FBSDKShareDialog dialog = new FBSDKShareDialog();
        dialog.setShareContent(content);
        dialog.show();
    }

This throws the error `Open Graph keys must be namespaced: books.book`

In the example everything looks correctly namespaced to me so I can't see why this error should be occurring.

**Comment by BlueRiverInteractive** [comment]
Looking at the code that throws this exception, it seems you have to use colons `:` for namespacing:
https://github.com/facebook/facebook-ios-sdk/blob/master/FBSDKShareKit/FBSDKShareKit/Internal/FBSDKShareUtility.m#L61

**Comment by WillCalderwood** [comment]
This error seems to becoming from the value rather than the key. I get the error

    Open Graph keys must be namespaced: A Game of Thrones

If I change the code to

    private void doSimpleShare() {
        FBSDKShareOpenGraphObject object = new FBSDKShareOpenGraphObject();
        object.putString("og:type", "books:book");
        object.putString("og:title", "A Game of Thrones");
        object.putString("og:description", "In the frozen wastes to the north of Winterfell, sinister and supernatural forces are mustering.");
        object.putString("books:isbn", "0-553-57340-3");

        FBSDKShareOpenGraphAction action = new FBSDKShareOpenGraphAction();
        action.setActionType("books.reads");
        action.putObject("books:book", object);

        FBSDKShareOpenGraphContent content = new FBSDKShareOpenGraphContent();
        content.setPreviewPropertyName("books:book");
        content.setAction(action);

        FBSDKShareDialog dialog = new FBSDKShareDialog();
        dialog.setShareContent(content);
        dialog.show();
    }
