### ISSUE TITLE
FBAdSize Not not bound

### ISSUE THREAD

**Issue by ASMCOM** [robovm/robovm-robopods#40]
I'm trying to add the FB Audience banners and keep getting app crashes at launch.

Code:
FBAdView adview = new FBAdView(Constants.PLACEMENT_ID_IOS, FBAdSize.Height50Banner(), rootViewController);

Error:
java.lang.UnsatisfiedLinkError: Optional @GlobalValue method org/robovm/pods/facebook/audience/FBAdSize.Height50Banner()Lorg/robovm/pods/facebook/audience/FBAdSize; not bound

**Comment by ASMCOM** [comment]
Any updates on this?

**Comment by BlueRiverInteractive** [comment]
Do you have a reproduction case/app? I can't reproduce this.
