### ISSUE TITLE
Google Mobile Ads for iOS 9

### ISSUE THREAD

**Issue by keskin** [robovm/robovm-robopods#43]
Are you planning to upgrade google mobile ads to latest version(7.5.1) for iOS 9 compability?
Until you upgrade the pods how can i use the latest ads framework? I try to change framework files on jar file but no luck. (Maybe I did wrong)

**Comment by matteberna** [comment]
+1

**Comment by BlueRiverInteractive** [comment]
Google Mobile ads has just been updated to the latest version (7.5.2). Just use the `1.9.1-SNAPSHOT` version to make use of the latest version.
