### ISSUE TITLE
Google Play Game Services - Apple Store rejection 

### ISSUE THREAD

**Issue by oldbriar** [robovm/robovm-robopods#44]
I'm trying to port my android game to ios with robovm and I'm using robopods for GPGS bindings.

When I tried signing-in to Google+, I noticed that it is handled by first forwarding the user to Safari/Google+ and redirecting back to my application after a successful login. I know that it is not allowed by Apple and applications got rejected.

Is there any other method in robopods other than routing to Safari/Google+ applications? Any way to utilize new Google iOS Sign-In sdk?

**Comment by syosan** [comment]
when Sign in, how to get the Auth Token using Google Play Game Services SDK?

**Comment by gilescoope** [comment]
The Google Play Games Services sdk now uses the Google SIgn In SDK for auth rather than this old method.

It would be good to know when the robopod binding will be updated.

**Comment by BlueRiverInteractive** [comment]
The RoboPod has been updated and you can now also use the Google SignIn SDK!
