### ISSUE TITLE
Include Deprecated Classes in Google Play Game Services Robopod

### ISSUE THREAD

**Issue by acr21** [robovm/robovm-robopods#45]
The AppState service is deprecated in Google Play Game Services but it is still functional so that games can migrate to the new Snapshot service. I am currently upgrading my game to the new service but I also need to support the old service so that user's data isn't lost. Please support the deprecated classes in Google Play Game Services.

**Comment by BlueRiverInteractive** [comment]
Can you point me to the obj-c header files of these deprecated classes? I can't seem to find them in the latest `gpg.framework`.

**Comment by acr21** [comment]
I just downloaded the SDK and cannot find the deprecated headers.

Google still has them listed here:

https://developers.google.com/games/services/ios/api/interface_g_p_g_app_state_model

but maybe when they mark it as deprecated that actually means removed.

Thanks for looking into it, I guess this is not possible.
