### ISSUE TITLE
Split Flurry in Analytics and Ads

### ISSUE THREAD

**Issue by obigu** [robovm/robovm-robopods#47]
Flurry RoboPod merges together Analytics and Ads which are independent. This can cause Apple rejections on app submission for apps that just want to use Analytics as Apple rejects apps that include advertising frameworks and don't display ads or those that don't declare they do as well as probably bigger app size and unnecessary dependencies.

On the other hand and as a separate discussion, Flurry ads are not very popular and maybe it should be evaluated if they're worth mantaining (if that helps getting resources for popular mediation layers such as HeyZap or MoPub for instance).

**Comment by BlueRiverInteractive** [comment]
Flurry has now been split into ads and analytics. Just use the correct maven artifact for your needs: (ends with either `ios`, `ios-ads` or `ios-analytics`). 
Please take a look at the readme: https://github.com/robovm/robovm-robopods/tree/master/flurry
