### ISSUE TITLE
HeyZap - Can't integrate via Gradle

### ISSUE THREAD

**Issue by ASMCOM** [robovm/robovm-robopods#49]
I have updated my build.gradle file with "compile org.robovm:robopods-heyzap-ios:1.9.0" and 
my iOS project have not been updated with the HeyZap bindings

**Comment by obigu** [comment]
Yes, it's not available through public repos yet, will we need to wait till next RoboVM version and download it manually in the meantime?

**Comment by BlueRiverInteractive** [comment]
New RoboPods are available as snapshot versions only until the next release of RoboVM.
So if you want to use Heyzap now, just use `"compile org.robovm:robopods-heyzap-ios:1.9.1-SNAPSHOT"`.
