### ISSUE TITLE
HeyZap bindings failed to launch on device

### ISSUE THREAD

**Issue by ASMCOM** [robovm/robovm-robopods#50]
So After I tryied to use the HeyZap bindings via Gradle with no success (https://github.com/robovm/robovm-robopods/issues/49) I decided to download th jar file.

While adding the jar file manually to my project helped me overcome my first issue I'm now getting the following error when trying to launch the app on iOS Device. 

> An internal error occurred during: "Launching new-game-ios". No
> @Marshaler found for return type of @Callback method
> <org.robovm.pods.heyzap.ads.HZAdMobBannerSupport:
> org.robovm.pods.google.mobileads.GADAdSize
> $cb$adSizeNamed$(org.robovm.objc.ObjCClass,org.robovm.objc.Selector,java.lang.String)>

**Comment by BlueRiverInteractive** [comment]
Because of the nature how Heyzap integrates with Admob, the google-mobile-ads RoboPod is required as a dependency to make it work. 
This should work automatically if you use the RoboPod as a Maven/Gradle dependency. Please try by using the `"org.robovm:robopods-heyzap-ios:1.9.1-SNASPHOT"`.

**Comment by ASMCOM** [comment]
It seems to be stuck while trying to download via gradle..

**Comment by obigu** [comment]
Add the SNAPSHOT repo to your repositories in the Gradle file

maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }

**Comment by ASMCOM** [comment]
I already did.

**Comment by ASMCOM** [comment]
For some reason the download time was very long... anyway, it's working fine now. Thanks!

**Comment by mbpriv** [comment]
Adding Google Mobile Ads 1.9.1-SNAPSHOT still results in:

`11/10/15 5:29:47 PM: [ERROR] Undefined symbols for architecture x86_64:
11/10/15 5:29:47 PM: [ERROR]   "_OBJC_CLASS_$_GGLContext", referenced from:
11/10/15 5:29:47 PM: [ERROR]       l_OBJC_$_CATEGORY_GGLContext_$_AdMob in libGGLAdMob.a(GGLContext+AdMob.o)
11/10/15 5:29:47 PM: [ERROR] ld: symbol(s) not found for architecture x86_64
11/10/15 5:29:47 PM: [ERROR] clang: error: linker command failed with exit code 1 (use -v to see invocation)
11/10/15 5:29:47 PM: [ERROR] Build failed`
