### ISSUE TITLE
Parse robopod using an older version of Parse iOS SDK

### ISSUE THREAD

**Issue by Davinaldo** [robovm/robovm-robopods#53]
Hello. I believe the parse 1.9.0 robopod was built using an earlier version of the Parse iOS SDK than the advertised SDK 1.9.1. 

I believe it could still be the previous 1.7.4 version that 1.6.0 robopod was built around.

Would you kindly double check this please?

**Comment by BlueRiverInteractive** [comment]
Have you tried to use the robopods snapshot version `1.9.1-SNAPSHOT`? The stable `1.9.0` robopods don't have the latest additions.

I've added a note to the README to make this more clear: 
https://github.com/robovm/robovm-robopods#snapshot-versions

**Comment by Davinaldo** [comment]
I've just tried them. Yes this does use the latest versions! Thanks.

Is the Snapshot version number something we work out for ourselves (i.e. + 0.0.1), or will this be a permanent updated feature of the landing page?

**Comment by BlueRiverInteractive** [comment]
I will try to keep the landing page updated :)
But generally speaking, yes the snapshot version will be stable version + 0.0.1-SNAPSHOT, so you can also work it out yourself. 
For example, once RoboVM 1.10 has been released, the snapshot version will be 1.10.1-SNAPSHOT.
