### ISSUE TITLE
HeyZap Binding - Banner not showing  

### ISSUE THREAD

**Issue by ASMCOM** [robovm/robovm-robopods#56]
Hi, I'm trying to view banner ads with HeyZap but it's not working for me, I have haded my code below is there anything wrong with it? and by the way... How can I set HeyZap To show test banner ads?

    @Override
    public boolean didFinishLaunching(UIApplication application, UIApplicationLaunchOptions launchOptions) {
        
    super.didFinishLaunching(application, launchOptions);
    
    // HeyZap Setup
    
    HeyzapAds.start("YOUR_PUBLISHER_ID");
    
    // HeyZap Banners
    
    rootViewController = application.getKeyWindow().getRootViewController();
    adViewController = new UIViewController();
    
    HZBannerAdOptions options = new HZBannerAdOptions();
    HZBannerAd.placeBannerInView(adViewController.getView(), HZBannerPosition.Bottom ,options, new VoidBlock1<HZBannerAd>() {
    
     @Override
     public void invoke(HZBannerAd a) {
     System.out.println("banner request success");
     }
    
     }, new VoidBlock1<NSError>() {
     @Override
     public void invoke(NSError a) {
     System.out.println("banner request failed " + a.description());
     }
     });
    
     // Adding the ad view controller to root view controller.
     rootViewController.addChildViewController(adViewController);
     rootViewController.getView().addSubview(adViewController.getView());
     application.getKeyWindow().setRootViewController(rootViewController);
     application.getKeyWindow().addSubview(rootViewController.getView());
     application.getKeyWindow().makeKeyAndVisible();
    
      return true;
        }

**Comment by BlueRiverInteractive** [comment]
I would recommend to use the HeyZap testing feature. It greatly helps to make sure all networks work.
After you start Heyzap `HeyzapAds.start("");` and have setup your root viewcontroller and window, call ` HeyzapAds.presentMediationDebugViewController();`

**Comment by BlueRiverInteractive** [comment]
What did the mediation debug view controller say? Could you fix the issue?
