### ISSUE TITLE
Add Robo.Billing

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm-robopods#70]
Most wanted cross-platform RoboPod according to survey.

**Comment by jtuta** [comment]
Hi, is there any ETA on this, is it worth starting to implement gdx-pay for libgdx app or should would be better to wait for this?

**Comment by BlueRiverInteractive** [comment]
@jtuta I just pushed the first version of Robo.Billing. It's still undocumented but you can give it a try. There is also a sample app in the snapshot branch that shows how to use the RoboPod: https://github.com/robovm/robovm-samples/tree/snapshot/robopods/components/robo.billing

Please report any issues or missing features. Thanks!

**Comment by jtuta** [comment]
Great news, I will. I don't think I will have problems with missing documentation. Can I help in any way? Unfortunately, I will be able only to test ios implementation, because my country is not supported by Google merchant account and I cannot implement IAPs in Android.

**Comment by BlueRiverInteractive** [comment]
Any testing will be very helpful! 
Just give it a try and post any issues you encounter, or features that you are missing. 
It should work totally fine with only iOS. However the Android part utilizes OpenIAB which allows alternative markets, like Amazon, Samsung, SlideME etc. I haven't tried them out myself yet but this may be an option for you to have IAPs on Android in your country too.
