### ISSUE TITLE
Facebook stories getting keys / values mixed up

### ISSUE THREAD

**Issue by WillCalderwood** [robovm/robovm-robopods#76]
The error suggests it's looking at the value expecting it to be the key. I get the error:

    Open Graph keys must be namespaced: A Game of Thrones

With the code

    private void doSimpleShare() {
        FBSDKShareOpenGraphObject object = new FBSDKShareOpenGraphObject();
        object.putString("og:type", "books:book");
        object.putString("og:title", "A Game of Thrones");
        object.putString("og:description", "In the frozen wastes to the north of Winterfell, sinister and supernatural forces are mustering.");
        object.putString("books:isbn", "0-553-57340-3");

        FBSDKShareOpenGraphAction action = new FBSDKShareOpenGraphAction();
        action.setActionType("books.reads");
        action.putObject("books:book", object);

        FBSDKShareOpenGraphContent content = new FBSDKShareOpenGraphContent();
        content.setPreviewPropertyName("books:book");
        content.setAction(action);

        FBSDKShareDialog dialog = new FBSDKShareDialog();
        dialog.setShareContent(content);
        dialog.show();
    }

**Comment by BlueRiverInteractive** [comment]
Good catch! Fixed in 1.12.1-SNAPSHOT.
