### ISSUE TITLE
Facebook 1.12.0 is using the web login instead of native

### ISSUE THREAD

**Issue by WillCalderwood** [robovm/robovm-robopods#77]
Facebook login was working fine until I upgraded to 1.12.0, at which point it reverted to using the web login instead of the native login. If I switch back to 1.9.0 then it works as expected.

My login code is just:

    loginManager.logInWithReadPermissions(FacebookApi.getDefaultPermissions(), loginListener);

**Comment by BlueRiverInteractive** [comment]
I think Facebook changed the default login mechanics in some of their latest version. I would recommend to check the official documentation, it may give a hint how to configure the login behavior: https://developers.facebook.com/docs/facebook-login/ios
