### ISSUE TITLE
Issue of google ads  

### ISSUE THREAD

**Issue by yx421626416** [robovm/robovm-robopods#80]
Hi, guys

When I followed the "Usage" you wrote, the version of SDK I downloaded from Gradle is 7.3, but the lasted one is 7.6. So there is no google adds in my project.

I tried to  copy the code to my project and replace the source of the SDK,but it did not  work.

Here is the details:
15-12-29 14:40:40: [ERROR] Undefined symbols for architecture armv7:
15-12-29 14:40:40: [ERROR]   "_OBJC_CLASS_$_GADInterstitial", referenced from:
15-12-29 14:40:40: [ERROR]       objc-class-ref in libGGLAdMob.a(GGLContext+AdMob.o)
15-12-29 14:40:40: [ERROR]   "_OBJC_CLASS_$_GADBannerView", referenced from:
15-12-29 14:40:40: [ERROR]       objc-class-ref in libGGLAdMob.a(GGLContext+AdMob.o)
15-12-29 14:40:40: [ERROR] ld: symbol(s) not found for architecture armv7
15-12-29 14:40:42: [ERROR] clang: error: linker command failed with exit code 1 (use -v to see invocation)
15-12-29 14:40:42: [ERROR] Build failed

How can I solve this problem to get the adds in my project.

**Comment by yx421626416** [comment]
Anybody can give me a hand,please?

**Comment by lijas** [comment]
Did you find an answer to this problem? I got the same now.
