### ISSUE TITLE
Add Heyzap binding

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm-robopods#9]

**Comment by ASMCOM** [comment]
Any idea when the Heyzap sdk will be binded?

**Comment by obigu** [comment]
Really interested on the Heyzap binding too, an estimation will be really helpful to determine if it's worth it to try to do the binding manually or wait for the RoboPod.

**Comment by BlueRiverInteractive** [comment]
No need to wait anymore, it's available :)
Check out the instructions on how to use it: https://github.com/robovm/robovm-robopods/tree/master/heyzap/ios

Happy coding!

**Comment by ASMCOM** [comment]
Thanks :)
