### ISSUE TITLE
Split Facebook into multiple poms (one per framework)

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm-robopods#98]
ios -> will contain all frameworks except for FBAudienceNetwork
ios-core -> FBSDKCoreKit
ios-login -> FBSDKLoginKit
ios-messenger -> FBSDKMessengerShareKit
ios-share -> FBSDKShareKit
ios-audience -> FBAudienceNetwork

**Comment by ASMCOM** [comment]
So how can I use the audince network?

**Comment by BlueRiverInteractive** [comment]
I forgot to include `ios-audience` in the list :) You will be able to use the `robopods-facebook-ios-audience ` for the audience network.

**Comment by ASMCOM** [comment]
And what about the FB analytics what will I need in order to use it?

**Comment by BlueRiverInteractive** [comment]
If you want just FB analytics, you can use the artifact robopods-facebook-ios-core or just robopods-facebook-ios.
If you also want FBAudienceNetwork, just add a dependency to robopods-facebook-ios-audience too.
